# Generated by Django 4.1.7 on 2023-03-16 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'permissions': [('can_add_new_category', 'can add new category')]},
        ),
    ]
