# Generated by Django 4.1.7 on 2023-03-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_itemcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='category_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
