# Generated by Django 4.1.7 on 2023-03-16 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_itemcategory_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'permissions': [('can_add_new_category', 'can add new category'), ('can_update_category', 'can update category')]},
        ),
    ]
