# Generated by Django 4.1.7 on 2023-03-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_itemcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': [('can_add_new_item', 'can add new item'), ('can_update_item', 'can update item')]},
        ),
    ]
