# Generated by Django 4.1.7 on 2023-03-17 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchnumber',
            options={'permissions': [('can_add_new_batch_number', 'can add new batch number'), ('can_update_batch_number', 'can update batch number')]},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'permissions': [('can_add_new_unit', 'can add new unit'), ('can_update_unit', 'can update unit')]},
        ),
    ]
