# Generated by Django 4.1.7 on 2023-03-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0002_requisition_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisition',
            options={'ordering': ['code']},
        ),
        migrations.RenameField(
            model_name='requestitem',
            old_name='requested',
            new_name='approved',
        ),
        migrations.AddField(
            model_name='requestitem',
            name='approved_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Pending', max_length=15),
        ),
    ]
