# Generated by Django 4.1.7 on 2023-03-21 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0003_alter_requisition_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestitem',
            name='requested_items_total',
        ),
        migrations.RemoveField(
            model_name='requestitem',
            name='requested_items_total_currency',
        ),
    ]
